### ISSUE TITLE
Insufficient code coverage does not make the process fail

### ISSUE THREAD

**Issue by prantlf** [MegaArman/tap-nyc#2]
If there is test failure, the process fails with the exit code `1` which is good. It is handled by the build task as a failure and the build stops:

```
$ ./node_modules/.bin/nyc ./node_modules/.bin/tape test/dependencies.test.js | ./node_modules/.bin/tap-nyc

    ✖ The message "nrecognised dependency: "dummy"." should start with "Unrecognised dependency:".
    ------------------------------------------------------------------------------------------------
      operator: ok
      expected: true
      actual:   false
      at: Test.<anonymous> (.../test/dependencies.test.js:18:12)
      stack: |-

ERROR: Coverage for branches (60%) does not meet global threshold (80%)

$ echo $?
1
```

If the coverage is too little, the process succeeds with the exit code `0` which is bad. It is handled by the build task as a success and the build goes on:

```
$ ./node_modules/.bin/nyc ./node_modules/.bin/tape test/dependencies.test.js | ./node_modules/.bin/tap-nyc
ERROR: Coverage for branches (60%) does not meet global threshold (80%)

  total:     3
  passing:   3

  duration:  799ms

$ echo $?
0
```

How about returning a failing exit code from the `tap-nyc` formatter, if the coverage does not meet the specified threshold?

**Comment by prantlf** [comment]
I found a workaround - do not let `nyc` to check the coverage and call `nyc check-coverage` after the tests finish. From `package.json`:

```js
"scripts": {
  "check": "node test/*.js",
  "test": "nyc npm run check && nyc check-coverage",
  ... 
}
```

**Comment by thealjey-eib** [comment]
@MegaArman, @prantlf  this just doesn't seem like an adequate solution to me.
Is there really no other way to make this work?

**Comment by thealjey-eib** [comment]
I have figured it out!
It is not a problem with `tap-nyc` specifically, but with a way that we are meant to apply tape reporters in general.
When you execute `nyc tape test/*.js | tap-nyc`, you think you are piping the result of `tape` to `tap-nyc`, when in reality you are piping the result of `nyc` itself.
So, if you do this instead, it will work:
```json
"scripts": {
  "check": "tape test/*.js | tap-nyc",
  "test": "nyc npm run check"
}
```

**Comment by MegaArman** [comment]
~~`nyc check-coverage && nyc tape tests/*.js | tap-nyc` is one way too~~

I actually run a linter before I do any testing `npm run lint && nyc tape tests/*.js | tap-nyc`
If the linter fails, then no testing happens.

**Comment by thealjey-eib** [comment]
but then, wouldn't that check for coverage before the tests are executed, and as such there is no coverage information yet (or one exists from a previous run)?

**Comment by MegaArman** [comment]
> but then, wouldn't that check for coverage before the tests are executed, and as such there is no coverage information yet (or one exists from a previous run)?

That's a very good point. I removed the .nyc_output dir and that command failed. It was in fact using the coverage from a previous run
